// =================================================
// This is an autogenerated file. 
// Please refrain from manually modifying this file.
// =================================================

export interface ISend {
    message: string;
}
export interface IReceive {
    timestamp: number;
}